[build]
publish="."
functions="netlify/functions"

[functions]
node_bundler="esbuild"

[build.environment]
NODE_VERSION="18"

[[headers]]
for="/.netlify/functions/holidays"
  [headers.values]
  Access-Control-Allow-Origin="*"
  Access-Control-Allow-Headers="Content-Type, Authorization"
  Access-Control-Allow-Methods="GET, POST, OPTIONS"
